---
- name: docker installation
  hosts: all
  become: true
  
  tasks:
  - name: adding docker repo
    copy:
      dest: /etc/yum.repos.d/docker.repo
      content: |
        [docker]
        name=docker-stable
        baseurl=https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck=false
        
  - name: installing docker
    yum:
      name: "docker-ce-18.09.1-3.e17.x86_64"
      state: present
      
  - name: starting docker
    service:
      name: docker
      state: started
      
  - name: enable docker
    service:
      name: docker
      enabled: true
...
     
